In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[8]

8

In [9]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [11]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

In [13]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [15]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [19]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [21]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [27]:
# Getting individual element value
arr_2d[1][0]

20

In [29]:
# Getting individual element value
arr_2d[1,0]

20

In [31]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [33]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [35]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [37]:
#Set up matrix
arr2d = np.zeros((10,10))

In [39]:
#Length of array
arr_length = arr2d.shape[1]

In [41]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [43]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [45]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [47]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [51]:
bool_arr = arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [53]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [55]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])