In [1]:
import numpy as np

In [3]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,6]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 6]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 6]])

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones(3)

array([1., 1., 1.])

In [21]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [25]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [27]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
np.random.rand(2)

array([0.23012285, 0.80972512])

In [31]:
np.random.rand(5,5)

array([[0.3349055 , 0.50082435, 0.06106542, 0.11479499, 0.70197073],
       [0.31185435, 0.94855129, 0.04459686, 0.87278706, 0.10199068],
       [0.08069363, 0.85655779, 0.58613415, 0.21411099, 0.36007437],
       [0.61450385, 0.49970677, 0.22030593, 0.51469625, 0.03571537],
       [0.57375462, 0.61623581, 0.27139648, 0.32177005, 0.57124036]])

In [33]:
np.random.randn(2)

array([-1.49371022, -0.03290212])

In [35]:
np.random.randn(5,5)

array([[-0.2755641 , -1.04251498, -1.10662067, -0.56819654, -0.17922777],
       [ 2.35822146,  1.0102145 , -0.63378476,  0.38263372, -0.48435885],
       [-0.97657187,  0.57369857,  0.42292114,  0.0719979 ,  1.54712553],
       [ 0.20598661,  0.73304457,  0.48176732, -2.35791507, -1.62659975],
       [-0.55972453,  0.67423716,  1.35798141, -0.1463771 , -0.39539858]])

In [37]:
np.random.randint(1,100,10)

array([75,  8, 19, 82, 88, 76, 17, 37, 27,  4])

In [39]:
np.random.randint(1,30)

12

In [41]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
ranarr

array([16, 20, 31, 22, 37, 24,  6,  0, 27, 48])

In [47]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
ranarr.max()

48

In [51]:
ranarr.argmax()

9

In [53]:
ranarr.min()

0

In [55]:
ranarr.argmin()

7

In [57]:
arr.shape

(25,)

In [59]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [61]:
arr.reshape(1,25).shape

(1, 25)

In [63]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [65]:
arr.reshape(25,1).shape

(25, 1)

In [67]:
arr.dtype

dtype('int64')